<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>disable</ImplicitUsings>
        <EnableDefaultItems>false</EnableDefaultItems>
    </PropertyGroup>

    <ItemGroup>
        <NpmPackageFile Include="package.json"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Include="node_modules\ecs.benchmark.frifloecs\Runtime\Benchmark.FrifloEcs\**\*.cs"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Benchmark.Core\Benchmark.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Friflo.Engine.ECS" Version="3.6.0" />
    </ItemGroup>

</Project>
