<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>9.0</LangVersion>
        <ImplicitUsings>disabled</ImplicitUsings>
        <Nullable>disable</Nullable>
        <EnableDefaultItems>false</EnableDefaultItems>
        <DefineConstants>$(DefineConstants);LEOECSLITE_NO_SANITIZE_CHECKS</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
        <NpmPackageFile Include="package.json"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Include="node_modules\com.leopotam.ecslite\src\*.cs"/>
    </ItemGroup>

</Project>
