<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>disable</ImplicitUsings>
        <EnableDefaultItems>false</EnableDefaultItems>
    </PropertyGroup>

    <ItemGroup>
        <NpmPackageFile Include="package.json"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Include="node_modules\ecs.benchmark.core\Runtime\Benchmark.Core\**\*.cs"/>
        <Compile Remove="node_modules\ecs.benchmark.core\Runtime\Benchmark.Core\SourceGenerators\**\*.cs"/>
    </ItemGroup>

</Project>
