<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>9.0</LangVersion>
        <ImplicitUsings>disable</ImplicitUsings>
        <EnableDefaultItems>false</EnableDefaultItems>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <NpmPackageFile Include="package.json"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Include="node_modules\ecs.benchmark.massiveecs\Runtime\Benchmark.MassiveEcs\**\*.cs"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Benchmark.Core\Benchmark.Core.csproj"/>
        <ProjectReference Include="..\..\Dependencies\Massive\Massive.csproj"/>
    </ItemGroup>

</Project>
