<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>Benchmark.Runner</RootNamespace>
        <OptimizationPreference>Speed</OptimizationPreference>
        <InvariantGlobalization>true</InvariantGlobalization>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BenchmarkDotNet.TestAdapter" Version="0.15.8"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.3.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Benchmark.Generator\Benchmark.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
        <ProjectReference Include="..\Benchmarks\Benchmark.*\Benchmark.*.csproj"/>
    </ItemGroup>

</Project>
