<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>disable</ImplicitUsings>
        <EnableDefaultItems>false</EnableDefaultItems>
    </PropertyGroup>

    <ItemGroup>
        <NpmPackageFile Include="package.json"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Include="node_modules\ecs.benchmark.morpeh\Runtime\Benchmark.Morpeh\**\*.cs"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Benchmark.Core\Benchmark.Core.csproj" />
        <PackageReference Include="Scellecs.Morpeh" Version="2024.1.1" />
    </ItemGroup>

</Project>
